### ISSUE TITLE
Legacy BIOS Ubuntud decrypt page appears

### ISSUE THREAD

**Issue by brs17** [pop-os/plymouth-theme#12]
It is possible to make the Ubuntu decrypt page appear on Pop!_OS on a machine in legacy bios mode.

Steps to reproduce the issue:
1. Turn the machine.
2. Reach the decrypt page.
3. Press the powerbutton to turn the machine off.
4. Turn the machine back on.
5. GRUB will appear even though it shouldn't without a key being pressed for it.
6. The Ubuntu decrypt page appears.

**Comment by leviport** [comment]
Closing because I haven't seen this happen in a long time.
