### ISSUE TITLE
21.04: Encryption prompt off center

### ISSUE THREAD

**Issue by leviport** [pop-os/plymouth-theme#19]
I upgraded my personal desktop over the weekend, and this started happening every time I boot. I'm suspecting it's related to my monitor layout. The left display is a 2560x1440p 144Hz display connected over DisplayPort, and the right display is a 1920x1080 in portrait mode connected over HDMI. My GPU is an AMD RX Vega64.

I didn't do any further testing since there were video games that needed playing, but I'll test different display configurations soon.

![PXL_20210514_234350065](https://user-images.githubusercontent.com/13512097/118527605-b2a46a00-b6fe-11eb-9d13-9753136ece45.jpg)

**Comment by jackpot51** [comment]
Strange it doesn't seem to line up on either monitor. And pre-X11 it shouldn't know the right one is rotated yet.

**Comment by bflanagin** [comment]
Also happens on galp5 and the lemp9. Possibly due to the different native display resolutions of the screens?

**Comment by ianhundere** [comment]
happening to me after updating to 21.04 from 20.10. 

doesn't show up at all via my laptop screen, but us off-center via my external monitors.

i have to press esc twice to see it centered again.

**Comment by ianhundere** [comment]
weird, i did a `update-initramfs -c -k all` and got an error saying `cryptsetup: WARNING: cryptdata: ignoring unknown option 'nofail'`

so i looked at my `crypttab` file and found `nofail` in it. i ended up removing it and not i don't have issues with the encryption prompt not showing up.

**Comment by ianhundere** [comment]
just to chime in again, this is still happening on my external monitor as per @leviport

**Comment by gjrtimmer** [comment]
I have the same problem, I've also put it here [Reddit](https://www.reddit.com/r/pop_os/comments/oknmkt/encryption_unlock_off_center/h5huxc5/?context=3)

So right now we have also figured out that if I remove my additional two screens, and just use my laptop screen I do not have the issue. What makes it weird is that is started since my upgrade to 21.04.

![20210714_081618](https://user-images.githubusercontent.com/6072255/126034061-a6eac384-3615-4c16-9402-3a9393b3ce93.jpg)

**Comment by gjrtimmer** [comment]
So I was searching; can this commit be the culprit https://github.com/pop-os/plymouth-theme/commit/ba4edf19faf88d019013746fe0b4ed724c23c20b#diff-d91a29052a1e731ad56359dd4031575130be146c057e16b385241073c2f647a1 ?

So anybody and suggestion how I can test this ?

**Comment by gjrtimmer** [comment]
Another one I found was for the pop-os upgrade.

https://github.com/pop-os/plymouth-theme/commit/cc2b8aee5f5cb77c1dfb42eccefd8b26247ab972#diff-d91a29052a1e731ad56359dd4031575130be146c057e16b385241073c2f647a1L20-L21

**Comment by gjrtimmer** [comment]
Any update ?

So can somebody please share how I can run this in some kind of development / testing mode ?
I would like to contribute because this issue has been open since May.

**Comment by jacobgkau** [comment]
> So can somebody please share how I can run this in some kind of development / testing mode ?

After you clone the repository and make any changes you want to test, you can install the build dependencies with `sudo apt build-dep pop-plymouth-theme`, then build the package with `dpkg-buildpackage -b -uc -us`.

**Comment by gjrtimmer** [comment]
@jacobgkau Thank you very much, just for clarity, after I build the package I can install it, is there an easy way / command to revert to the official / current ?

**Comment by jacobgkau** [comment]
> @jacobgkau Thank you very much, just for clarity, after I build the package I can install it, is there an easy way / command to revert to the official / current ?

You would install the package with `sudo dpkg -i ./package.deb` and revert to current with `sudo apt upgrade`.

**Comment by gjrtimmer** [comment]
@jacobgkau Thank you

**Comment by 13r0ck** [comment]
Should be closed because of #25
