### ISSUE TITLE
Laptops w/ switchable Nvidia hardware do not boot properly with the lid closed

### ISSUE THREAD

**Issue by wagnerck** [pop-os/plymouth-theme#26]
Distribution;
21.10

Test Hardware:
Oryx Pro (oryp6)

Issue/Bug Description:
We've had reports that System76 laptops running Pop!OS and that have switchable Nvidia graphics are not behaving properly on reboot when the lid is shut. I have replicated the problem on my Oryx Pro (oryp6).

There appears to be at least two parts to this problem.

The first is that the prompt to unlock the encrypted drive does not show up on an external monitor after reboot, which is obviously a problem if the lid is closed. This appears to be because the Nvidia kernel modules are not being added to the boot image by the driver package.

The _nvidia-driver-470_ driver package (and possibly other versions) copies the .ko files to the correct location, but I can confirm with _lsinitramfs /boot/initrd.img_ that they are not added to the boot image by default. This means that during a reboot or cold boot, the unlock prompt can only appear on the laptop display using the Intel integrated graphics, as only the i915 kernel modules are loaded.

A workaround for this is to manually add the following to _/etc/initramfs-tools/modules_:
* nvidia
* nvidia_uvm
* nvidia_drm
* nvidia_modeset

Then run _update-initramfs -u_ to update the boot image, and reboot. It now shows the unlock prompt on my external monitor, even with the lid closed. The prompt is off-center, which is a known issue but a less critical one.

This is not a particularly good solution, as what I think needs to happen is an update to the driver package, so it adds the appropriate kernel modules to the boot image.

This may also be related to this other issue, although this one doesn't specifically mention the lid being closed: https://github.com/pop-os/plymouth-theme/issues/18

The second part of the problem is that after unlocking the system, it attempts to go back to sleep at multiple points during the boot process. It tries to sleep before the GDM login screen appears, and sometimes you can wake it up properly with the keyboard and then use that screen to login. It will then try to sleep again while it loads the desktop environment, and sometimes you can wake it up and get a usable system. Other times, however, the laptop doesn't wake up back correctly at either of these two points and the laptop has to be powered off and back on with the lid open.

A workaround for this second issue is to edit _/etc/systemd/logind.conf_ and change _HandleLidSwitchExternalPower_ to the "ignore" setting (as it is set to "suspend" by default). The _HandleLidSwitchDocked_ setting was already set to "ignore", but apparently it doesnt consider just having an external monitor as "docked", at least on this hardware. I've tested this with my monitor connected via the Oryx Pro HDMI port, the miniDisplayPort connector, and an HDMI port on a USB-C hub (i.e. "DisplayPort Alt Mode") and the same problem occurs with each.

According to the docs for _logind.conf_, having an external display attached _should_ count as docked as far as systemd is concerned:

> If the system is inserted in a docking station, or if more than one display is connected, the action specified by HandleLidSwitchDocked= occurs; if the system is on external power the action (if any) specified by HandleLidSwitchExternalPower= occurs; otherwise the HandleLidSwitch= action occurs.

So I think that figuring out why systemd doesn't realize there's an external display attached is the real fix here, because that way we can leave _logind.conf_ at the defaults, with predictable behavior. Alternatively, exposing _HandleLidSwitchExternalPower_ (and possibly _HandleLidSwitchDocked_) in the power settings is another option that would allow users to better specify the behavior they want.

However, it does seem that Pop!OS is not the only distro having these problems, as there are related issues with _logind.conf_ and external monitors within the main systemd repo (https://github.com/systemd/systemd/pull/19490, https://github.com/systemd/systemd/issues/12001, and others), so exposing this behavior via the power settings may be our best bet here?

**Comment by 13r0ck** [comment]
Just linking #21 and #27 here. Plymouth seems to generally struggle with monitors

**Comment by wagnerck** [comment]
Been doing some additional research on this.

On a hybrid graphics laptop that's using `system76-power`, adding the appropriate Nvidia kernel modules to `/etc/initramfs-tools/modules` causes a problem when switching to Integrated Graphics mode. The `nvidia.ko` module loads anyway, even though it's blacklisted via `/etc/modprobe.d/system76-power.conf`, so the system actually ends up in Compute Graphics mode instead, sortof. Things like the `nvdec` video decoder work but other things don't. So clearly changing the driver packages so the Nvidia kernel modules _always_ get added to the boot image is not the right path for solving the problem.

My thought here is that `system76-power` could also add a script to the `/etc/initramfs-tools/hooks` folder, in the same way it adds `system76-power.conf` to `/etc/modprobe.d/`. The `hooks` folder operates in a similar way, although it contains scripts and not config files. See the section on hook scripts at https://manpages.ubuntu.com/manpages/xenial/man8/initramfs-tools.8.html for details. This way `system76-power` can add or remove the Nvidia kernel modules to and from the boot image as appropriate when the graphics mode is changed.

Still researching the issues with `HandleLidSwitchDocked` and the related settings.

**Comment by 13r0ck** [comment]
I kinda doubt it will change much, but does #28 help?

**Comment by wagnerck** [comment]
So far, no. I don't think changes to plymouth are going to help when the display doesn't show up on an external monitor at all, which it won't unless the kernel modules are present in the initrd boot image.

Just for reference, I've attached a couple of demonstration photos. The first is the system booted up, with the displays mirroring, the second is what happens on reboot with no changes to the cabling, etc. After unlocking the encrypted partition, the Nvidia modules load and the GDM login screen comes up normally.

![IMG_0133](https://user-images.githubusercontent.com/96320715/155866821-3be779a8-21ef-4d2d-b7cd-96108036bf28.jpg)
![IMG_0134](https://user-images.githubusercontent.com/96320715/155866825-002ed1af-7459-4dc8-803c-35a9ec48aee1.jpg)

And yes, the same thing happens with the new plymouth theme. This is what it looks like when I've added the Nvidia kernel modules via a placeholder script using `manual_add_modules` in `/etc/initramfs-tools/hooks` as a temporary fix (although I took this photo after reverting back to the regular plymouth theme):

![IMG_0135](https://user-images.githubusercontent.com/96320715/155869111-4df477d5-c683-4041-829e-1f8939742eac.jpg)

This is obviously not a huge problem if the laptop is open, but mine normally stays closed and put away under the monitor stand, and I can't imagine I'm the only person experiencing this. And unfortunately I don't think anyway we can do to plymouth is going to fix this, unless there's a way to have it load a kernel module that's not in the initrd boot image, and I don't think that's possible.

Semi-related, here's another odd thing I've found while experimenting with boot images. The initramfs hook file `/usr/share/initramfs-tools/hooks/framebuffer-nvidia` (which is installed from the `nvidia-kernel-common-510` package) looks like it _should_ be adding the appropriate nvidia kernel modules to initramfs, but it's not. It's only pulling modules from `/usr/lib/modules/[whatever]/updates/dkms`, which on Pop contains some system76 kernel modules but nothing from Nvidia. And I suspect it was meant to load `nvidiafb.ko` anyway, which is not what we want. This _appears_ to have been inherited from the Ubuntu driver re-packaging (https://github.com/NVIDIA/ubuntu-packaging-nvidia-driver/blob/main/debian/framebuffer-nvidia) and it's not present anywhere in the binaries you can get from Nvidia. It was commited in 2017 with the note "Add scripts from the previous packaging" so I kind of suspect this is just junk DNA, so to speak.

Anyway. If you think it's worthwhile, I've looked at the scripting behind `system76-power` and it would seem to be relatively easy to have the graphics mode switching also drop a custom file into `/etc/initramfs-tools/hooks`, since it's already doing the same thing with `/etc/modprobe.d/`. I can do a pull request on 'system76-power' that adds that functionality, and have it refer back to this issue?

**Comment by wagnerck** [comment]
Started working on a pull request: https://github.com/cwsystem76/system76-power/blob/master/src/graphics.rs

**Comment by 13r0ck** [comment]
trying to make a TLDR, is this correct?

1. Boot machine with display connected
2. close lid
3. reboot
Issue: Plymouth decryption screen doesn't show on external monitor

What graphics mode must the laptop be in?

**Comment by 13r0ck** [comment]
> Started working on a pull request: https://github.com/cwsystem76/system76-power/blob/master/src/graphics.rs

That is just a fork, go ahead an make a PR, just mark it as a draft if you are still working on it. It is easier to have discussion about it when it is a PR

**Comment by wagnerck** [comment]
That's a good TL;DR, yeah. It would also theoretically do the same thing as a cold boot with the lid closed, but I can't test that on an oryp6 because the power button is inaccessible.

There's more to the problem, though, as the laptop tries to go to sleep due to the closed lid before it gets to GDM, and between GDM and the desktop environment. I'm also looking into solutions for that, as systemd doesn't appear to be registering that a display is plugged into until it gets into the desktop environment.

And yeah, I know it's just a fork, I'm still working on it before I actually submit it as a PR. I'll go ahead and submit it as a draft in a bit.

**Comment by 13r0ck** [comment]
I believe this was fixed in system76-power / firmware.
