### ISSUE TITLE
What happened to the pop-logo theme?

### ISSUE THREAD

**Issue by spxak1** [pop-os/plymouth-theme#30]
Has the pop-logo theme now completely been removed? 
The version installed from ISO stopped working after the latest update (falling back to ubuntu-text, horribly). Once the package is removed with ```sudo apt remove plymouth-theme-pop-logo``` there is no candidate to reinstall it.

Has it now been complete removed?

Thank you.

**Comment by jacobgkau** [comment]
It hasn't been used or supported for a long time, so it was likely just forgotten about (or stripped out intentionally) when the main theme was rewritten recently.

You can view the last commit before the rewrite here: https://github.com/pop-os/plymouth-theme/tree/74e97d9d2a90b8eea3d25a9eafc055660b1ec0a2

**Comment by 13r0ck** [comment]
The pop-logo theme was written using plymouth script. With the recent rewrite of the plymouth theme to be more reliable we went with the two-step module as it's base. This meant that using the old pop-logo theme wouldn't receive the fixes from the new theme. 

Two-step does support animations and it should be possible to recreate something similar to the old pop-logo theme by modifying the [.plymouth file](https://github.com/pop-os/plymouth-theme/blob/master/pop-basic/pop-basic.plymouth) and adding the animation frames into the folder.

There are currently no plans to rebuild the old theme using two-step, but @spxak1 if you would like to I would be happy to help you. [elementary's plymouth theme](https://github.com/elementary/plymouth-theme) would be a good place to start. If you are interested feel free to re-open this issue with any questions you may have!

**Comment by andy0130tw** [comment]
AFAIK pop-logo already used the two-step module, as seen [here](https://github.com/pop-os/plymouth-theme/blob/74e97d9d2a/usr/share/plymouth/themes/pop-logo/pop-logo.plymouth). It can be revived by adding the deleted images back to the original directory, but I believe that some fine-tuning may be required.

**Comment by TermoZour** [comment]
I tried adding the animation frames back and it does work, albeit my system will only show the loading bar reach 100% then I'm dumped to the login manager. 

For faster systems I'd go with a BGRT theme with just a spinner, like Windows. On UEFI systems it will show the firmware logo and the stylized Pop!_OS spinner (if we have one).
