### ISSUE TITLE
Plymouth theme not appearing at boot.

### ISSUE THREAD

**Issue by akshymalvia** [pop-os/plymouth-theme#4]
The Plymouth theme **"pop-logo"** does not appears at boot up, instead shows detailed boot sequence.

**Comment by akshymalvia** [comment]
It happened after I upgraded from Pop 17.10 to 18.04. It's working properly before that.

**Comment by brs17** [comment]
Thank you for filing this issue @akshymalvia . An issue already exists regarding this, feel free to follow along with the conversation there: https://github.com/pop-os/iso/issues/205
